#!/bin/sh

git stash -q --keep-index

echo "Running git pre-commit hook"

./gradlew lint &&
node --env-file=.env ./scripts/check-commit-mail.js &&
node ./scripts/validate-branch-name.js

RESULT=$?

git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0