---
name: Linting

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest

    permissions:
          contents: read
          packages: read
          statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - run: ./gradlew lint
      - name: Lint Foundation module
        uses: yutailang0119/action-android-lint@v4
        with:
          report-path: foundation/build/reports/*.xml
      - name: Lint Components module
        uses: yutailang0119/action-android-lint@v4
        with:
          report-path: components/build/reports/*.xml
